jobs:
  main:
    image: node:6
    matrix:
      FILE: [test/first.test.js, test/second.test.js]
    steps:
      - install: npm install
      - foobar: echo $FILE
      # - test: npm test -- {{FILE}}
