jobs:
  main:
    image: node:{{NODE_VERSION}}
    matrix:
      NODE_VERSION:
        - 6
        - 7
      FILE:
        - test/first.test.js
        - test/second.test.js
    steps:
      - install: npm install
      - env: echo $NODE_VERSION
      - test: npm test -- $FILE
